
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbitpass!"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672  # rabbitmq
      - 15672:15672  # admin console

volumes:
  rabbitmq-data:
