version: '3'

services:
  database:
    container_name: postgres_db
    build: ./
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aleksei -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 834usachev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: strong_password
    networks: 
      - net


networks:
  net:
    name: postgres_network
    driver: bridge

