version: "3"

services:
  database:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "aleksei"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      # - ./backup/:/usr/local/pg_dump/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aleksei -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

