version: "3"

services:
  s3_storage:
    container_name: minio
    image: minio/minio:latest
    entrypoint: sh
    command: -c "mkdir -p /data/my-new-bucket && minio server /data --console-address :9001"
    restart: always
    environment:
      MINIO_ROOT_USER: "minio_user"
      MINIO_ROOT_PASSWORD: "minio_pass"
    # volumes:
    #   - ./minio_backup:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - net

networks:
  net:
    name: minio_network
    driver: bridge
