
services:
  redis:
    image: redis:7.4.1
    container_name: redis
    env_file:
      - .env
    volumes:
      - redis-data:/data
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  redis-data:
